export interface RawPartyUser {
  ma_so_nhan_vien: string;
  stt: string;
  ho_ten: string;
  ten: string;
  chi_bo: string;
  doi_tuong: string;
  nam_sinh: string;
  dan_toc_ton_giao: string;
  que_quan: string;
  trinh_do_hoc_van: string;
  trinh_do_ly_luan: string;
  chuc_vu: string;
  ngay_vao_dang: string;
  ngay_chinh_thuc: string;
  email: string;
}

export const rawUsers: RawPartyUser[] = [
  {
    ma_so_nhan_vien: "00094600",
    stt: "1",
    ho_ten: "Khuất Đức Anh",
    ten: "Anh",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "15/8/1986",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "Trung Sơn Trầm, Sơn Tây, Hà Nội",
    trinh_do_hoc_van: "Đại học",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "9/3/2018",
    ngay_chinh_thuc: "9/3/2019",
    email: "AnhKD3@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00074247",
    stt: "2",
    ho_ten: "Lê Thị Phương Anh (Chi ủy viên)",
    ten: "Anh",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FE HO",
    nam_sinh: "1989-07-10 00:00:00",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "Xã Quỳnh Giang, Huyện Quỳnh Lưu, Tỉnh Nghệ An",
    trinh_do_hoc_van: "Thạc sỹ",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "2011-06-10 00:00:00",
    ngay_chinh_thuc: "2012-06-10 00:00:00",
    email: "anhltp3@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00011279",
    stt: "3",
    ho_ten: "Nguyễn Kim Ánh",
    ten: "Ánh",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FE HO",
    nam_sinh: "07/1/1956",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "X, Đình Bảng, H.Từ Sơn, T. Bắc Ninh",
    trinh_do_hoc_van: "Tiến sỹ",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "1982-08-12 00:00:00",
    ngay_chinh_thuc: "1984-08-06 00:00:00",
    email: "kimanh@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00038637",
    stt: "4",
    ho_ten: "Ngô Văn Bình",
    ten: "Bình",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "30/08/1977",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "X. Dương Quang, H. Gia Lâm, TP. Hà Nội",
    trinh_do_hoc_van: "Thạc sỹ",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "05/08/2008",
    ngay_chinh_thuc: "05/08/2009",
    email: "BinhNV11@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00239520",
    stt: "5",
    ho_ten: "Nguyễn Đức Chính",
    ten: "Chính",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "16/06/1985",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "X. Cấn Hữu, H. Quốc Oai, TP. Hà Nội",
    trinh_do_hoc_van: "",
    trinh_do_ly_luan: "",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "4/9/2018",
    ngay_chinh_thuc: "4/9/2019",
    email: "chinhnd14@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00283903",
    stt: "6",
    ho_ten: "Lê Mai Đông",
    ten: "Đông",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "22/06/1979",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "X. Phương Trung, H. Thanh Oai, TP. Hà Nội",
    trinh_do_hoc_van: "",
    trinh_do_ly_luan: "",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "30/12/2011",
    ngay_chinh_thuc: "30/12/2012",
    email: "donglm6@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00272917",
    stt: "7",
    ho_ten: "Đặng Minh Đức",
    ten: "Đức",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "09/12/1984",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "X. Tiên Ngoại, H. Duy Tiên, T. Hà Nam",
    trinh_do_hoc_van: "Đại học",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "11/06/2009",
    ngay_chinh_thuc: "11/06/2010",
    email: "ducdm39@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00215633",
    stt: "8",
    ho_ten: "Nguyễn Văn Đường",
    ten: "Đường",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "15/9/1989",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "TT. Nam Giang, H. Nam Trực, T. Nam Định",
    trinh_do_hoc_van: "",
    trinh_do_ly_luan: "",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "18/1/2017",
    ngay_chinh_thuc: "18/1/2018",
    email: "duongnv44@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00011074",
    stt: "9",
    ho_ten: "Phạm Tuyết Hạnh Hà",
    ten: "Hà",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FE HO",
    nam_sinh: "29/10/1984",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "Cấp Tiến, Tiên Lãng, Hải Phòng",
    trinh_do_hoc_van: "Thạc sỹ",
    trinh_do_ly_luan: "Trung cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "2006-05-06 00:00:00",
    ngay_chinh_thuc: "2007-05-06 00:00:00",
    email: "HaPTH@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00176002",
    stt: "10",
    ho_ten: "Trịnh Thị Hà",
    ten: "Hà",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FE HO",
    nam_sinh: "1979-05-04 00:00:00",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "Yên Thọ, Yên Định, Thanh Hóa",
    trinh_do_hoc_van: "Thạc sỹ",
    trinh_do_ly_luan: "",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "12/2/2016",
    ngay_chinh_thuc: "12/2/2017",
    email: "hatt57@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00283854",
    stt: "11",
    ho_ten: "Đào Thúy Hà",
    ten: "Hà",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "17/05/1977",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "P. Lam Sơn, TP. Hưng Yên, T. Hưng Yên",
    trinh_do_hoc_van: "Tiến sỹ",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "10/08/2016",
    ngay_chinh_thuc: "10/08/2017",
    email: "hadt72@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00037801",
    stt: "12",
    ho_ten: "Lê Thanh Hải",
    ten: "Hải",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "21/12/1976",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "Minh Trí, Sóc Sơn, Hà Nội",
    trinh_do_hoc_van: "Thạc sỹ",
    trinh_do_ly_luan: "Cao cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "2005-10-03 00:00:00",
    ngay_chinh_thuc: "2006-10-03 00:00:00",
    email: "HaiLT10@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00120526",
    stt: "13",
    ho_ten: "Đặng Văn Hiếu",
    ten: "Hiếu",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "25/08/1986",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "xã Lương Phong, Hiệp Hòa,  Bắc Giang",
    trinh_do_hoc_van: "Thạc sĩ",
    trinh_do_ly_luan: "",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "11/10/2013",
    ngay_chinh_thuc: "11/10/2014",
    email: "hieudv2@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00067621",
    stt: "14",
    ho_ten: "Bùi Trung Hiếu",
    ten: "Hiếu",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "12/12/1984",
    dan_toc_ton_giao: "Kinh\nKhông",
    que_quan: "X. Hương Nôn, H. Tam Nông, T. Phú Thọ",
    trinh_do_hoc_van: "Tiến sỹ",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "22/12/2020",
    ngay_chinh_thuc: "22/12/2021",
    email: "hieubt18@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00168094",
    stt: "15",
    ho_ten: "Nguyễn Thị Hồng (Chi ủy viên)",
    ten: "Hồng",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FE HO",
    nam_sinh: "1984-09-05 00:00:00",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "Cấn Hữu, Quốc Oai, Hà Nội",
    trinh_do_hoc_van: "",
    trinh_do_ly_luan: "",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "13/01/2012",
    ngay_chinh_thuc: "13/01/2013",
    email: "HongNT70@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00029301",
    stt: "16",
    ho_ten: "Phan Duy Hùng",
    ten: "Hùng",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "24/5/1978",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "Thạch Mỹ - Thạch Hà - Hà Tĩnh",
    trinh_do_hoc_van: "Tiến sỹ",
    trinh_do_ly_luan: "Trung cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "2012-08-06 00:00:00",
    ngay_chinh_thuc: "2013-06-08 00:00:00",
    email: "HungPD2@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00182426",
    stt: "17",
    ho_ten: "Nguyễn Doãn Hưởng",
    ten: "Hưởng",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "25/2/1985",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "Đồng Bụt, Ngọc Liệp, Quốc Oai, Hà Nội",
    trinh_do_hoc_van: "",
    trinh_do_ly_luan: "",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "2011-02-09 00:00:00",
    ngay_chinh_thuc: "2012-02-09 00:00:00",
    email: "HuongND13@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00272926",
    stt: "18",
    ho_ten: "Vũ Văn Huy",
    ten: "Huy",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "13/11/1982",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "X. An Đổ, H. Bình Lục, T. Hà Nam",
    trinh_do_hoc_van: "Tiến sỹ",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "20/01/2011",
    ngay_chinh_thuc: "20/01/2012",
    email: "huyvv10@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00170699",
    stt: "19",
    ho_ten: "Nguyễn Thị Thanh Huyền",
    ten: "Huyền",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "30/10/1990",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "P. Trung Hòa, Q. Cầu Giấy, TP. Hà Nội",
    trinh_do_hoc_van: "",
    trinh_do_ly_luan: "",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "18/4/2018",
    ngay_chinh_thuc: "18/4/2019",
    email: "HuyenNTT97@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00025292",
    stt: "20",
    ho_ten: "Nguyễn Thị Thu Lan",
    ten: "Lan",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "16/10/1979",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "Hoằng Đại, Hoằng Hóa, Thanh Hóa",
    trinh_do_hoc_van: "Tiến sỹ",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "19/7/2004",
    ngay_chinh_thuc: "19/7/2005",
    email: "LanNTT2@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00175236",
    stt: "21",
    ho_ten: "Vương Thị Mỹ Ly",
    ten: "Ly",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "06/10/1995",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "X. Lại Thượng, H. Thạch Thất, TP. Hà Nội",
    trinh_do_hoc_van: "Đại học",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "20/06/2017",
    ngay_chinh_thuc: "20/06/2018",
    email: "lyvtm@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00241982",
    stt: "22",
    ho_ten: "Ngô Trường Minh",
    ten: "Minh",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "13/12/1985",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "X. Thọ Nghiệp, H. Xuân Trường, T. Nam Định",
    trinh_do_hoc_van: "Thạc sỹ",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "09/03/2018",
    ngay_chinh_thuc: "09/03/2019",
    email: "minhnt79@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00074119",
    stt: "23",
    ho_ten: "Kiều Văn Nam (Phó Bí thư)",
    ten: "Nam",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "01/02/1991",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "X. Cần Kiệm, H. Thạch Thất, TP. Hà Nội",
    trinh_do_hoc_van: "Thạc sỹ",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "04/12/2013",
    ngay_chinh_thuc: "04/12/2014",
    email: "NamKV@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00014648",
    stt: "24",
    ho_ten: "Lê Thị Thanh Nga",
    ten: "Nga",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "1980-10-06 00:00:00",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "Tân Tiến - Văn Giang - Hưng Yên",
    trinh_do_hoc_van: "Thạc sỹ",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "29/3/2014",
    ngay_chinh_thuc: "29/03/2015",
    email: "NgaLTT2@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00038042",
    stt: "25",
    ho_ten: "Giáp Thị Quỳnh Nga",
    ten: "Nga",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "1985-08-06 00:00:00",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "Việt Ngọc - Tân Yên - Bắc Giang",
    trinh_do_hoc_van: "Thạc sỹ",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "29/3/2014",
    ngay_chinh_thuc: "29/03/2015",
    email: "NgaGTQ@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00034224",
    stt: "26",
    ho_ten: "Đào Thị Thanh Nga",
    ten: "Nga",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FE HO",
    nam_sinh: "15/02/1984",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "Song Lãng – Vũ Thư – Thái Bình",
    trinh_do_hoc_van: "Đại học",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "2016-01-10 00:00:00",
    ngay_chinh_thuc: "2017-01-10 00:00:00",
    email: "NgaDTT7@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00167867",
    stt: "27",
    ho_ten: "Trần Thị Thanh Nga",
    ten: "Nga",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FE HO",
    nam_sinh: "7/11/1982",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "Gia Van, Gia Viễn, Ninh BÌnh",
    trinh_do_hoc_van: "",
    trinh_do_ly_luan: "",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "29/12/2010",
    ngay_chinh_thuc: "29/12/2011",
    email: "NgaTTT22@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00286509",
    stt: "28",
    ho_ten: "Tạ Thị Thanh Ngân",
    ten: "Ngân",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FE HO",
    nam_sinh: "21/10/1992",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "X. Trầm Lộng, H. Ứng Hòa, TP. Hà Nội",
    trinh_do_hoc_van: "Đại học",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "16/06/2016",
    ngay_chinh_thuc: "16/06/2017",
    email: "nganttt32@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00040306",
    stt: "29",
    ho_ten: "Lê Thanh Ngân (Phó Bí thư)",
    ten: "Ngân",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FE HO",
    nam_sinh: "23/9/1984",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "Đồng Mai - Hà Đông - Hà Nội",
    trinh_do_hoc_van: "Thạc sỹ",
    trinh_do_ly_luan: "Trung cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "30/11/2010",
    ngay_chinh_thuc: "30/11/2011",
    email: "nganlt8@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00047107",
    stt: "30",
    ho_ten: "Nguyễn Mạnh Nguyên",
    ten: "Nguyên",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "28/11/1988",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "Vạn Thắng, Ba Vì, Hà Nội",
    trinh_do_hoc_van: "Thạc sỹ",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "2016-01-10 00:00:00",
    ngay_chinh_thuc: "2017-01-10 00:00:00",
    email: "NguyenNM2@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00176102",
    stt: "31",
    ho_ten: "Phạm Thanh Tâm",
    ten: "Tâm",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "28/10/1980",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "Xã Võng Xuyên, huyện Phúc Thọ, TP Hà Nội",
    trinh_do_hoc_van: "Tiến sĩ",
    trinh_do_ly_luan: "",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "30/06/2016",
    ngay_chinh_thuc: "30/06/2017",
    email: "TamPT25@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00270621",
    stt: "32",
    ho_ten: "Trần Quang Thắng",
    ten: "Thắng",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "11/08/1971",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "X. Canh Tân, H. Hưng Hà, T. Thái Bình",
    trinh_do_hoc_van: "Tiến sỹ",
    trinh_do_ly_luan: "Trung cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "20/12/2002",
    ngay_chinh_thuc: "20/12/2003",
    email: "thangtq27@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00196051",
    stt: "33",
    ho_ten: "Phạm Văn Thanh",
    ten: "Thanh",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "02/10/1996",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "An Thượng, Hoài Đức, Hà Nội",
    trinh_do_hoc_van: "",
    trinh_do_ly_luan: "",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "03/9/2022",
    ngay_chinh_thuc: "03/9/2023",
    email: "thanhpv24@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00036119",
    stt: "34",
    ho_ten: "Nguyễn Thị Thơi",
    ten: "Thơi",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "31913",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "Xuân Lai - Gia Bình - Bắc Ninh",
    trinh_do_hoc_van: "Đại học",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "2014-03-29 00:00:00",
    ngay_chinh_thuc: "29/03/2015",
    email: "ThoiNT@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00016069",
    stt: "35",
    ho_ten: "Trần Thị Thúy",
    ten: "Thúy",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FE HO",
    nam_sinh: "1979-03-06 00:00:00",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "Vũ Hội, Vũ Thư, Thái Bình",
    trinh_do_hoc_van: "Tiến sỹ",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "22/5/2007",
    ngay_chinh_thuc: "22/5/2008",
    email: "thuytt5@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00027278",
    stt: "36",
    ho_ten: "Đỗ Thị Minh Thủy (Bí thư)",
    ten: "Thủy",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FE HO",
    nam_sinh: "1980-08-22 00:00:00",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "Trực Mỹ - Nam Ninh - Nam Định",
    trinh_do_hoc_van: "Thạc sỹ",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "2014-03-29 00:00:00",
    ngay_chinh_thuc: "29/03/2015",
    email: "ThuyDTM@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00035722",
    stt: "37",
    ho_ten: "Vũ Thị Thanh Thủy",
    ten: "Thủy",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "31/10/1979",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "X.Vĩnh An, H. Vĩnh Bảo, TP. Hải Phòng",
    trinh_do_hoc_van: "Tiến sỹ",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "20/10/2005",
    ngay_chinh_thuc: "20/10/2006",
    email: "ThuyVTT3@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00282910",
    stt: "38",
    ho_ten: "Phùng Thị Thu Trang",
    ten: "Trang",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FE HO",
    nam_sinh: "25/06/1982",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "X. Hoàng Đan, H. Tam Dương, T. Vĩnh Phúc",
    trinh_do_hoc_van: "12/12",
    trinh_do_ly_luan: "",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "12/03/2012",
    ngay_chinh_thuc: "12/02/2013",
    email: "trangptt66@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00261081",
    stt: "39",
    ho_ten: "Bùi Thị Anh Vân",
    ten: "Vân",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "11/09/1990",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "X. Cốc Thành, H. Vụ Bản, T. Nam Định",
    trinh_do_hoc_van: "Thạc sỹ",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "19/09/2022",
    ngay_chinh_thuc: "",
    email: "vanbta@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00265080",
    stt: "40",
    ho_ten: "Vũ Bảo Xuân",
    ten: "Xuân",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FE HO",
    nam_sinh: "10/07/2000",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "X. Hồng Dũng, H. Thái Thụy, T. Thái Bình",
    trinh_do_hoc_van: "Đại học",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "21/09/2022",
    ngay_chinh_thuc: "",
    email: "xuanvb@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00272920",
    stt: "41",
    ho_ten: "Nguyễn Thị Hoàng Yến",
    ten: "Yến",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "08/11/1986",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "TT. Hồ, H. Thuận Thành, T. Bắc Ninh",
    trinh_do_hoc_van: "Đại học",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "Đảng viên chính thức",
    ngay_vao_dang: "15/09/2011",
    ngay_chinh_thuc: "15/09/2012",
    email: "yennth126@fe.edu.vn",
  },
  {
    ma_so_nhan_vien: "00123456",
    stt: "42",
    ho_ten: "Võ Anh Hoàng",
    ten: "Hoàng",
    chi_bo: "Chi bộ Khối Giáo dục 2",
    doi_tuong: "CBGV FPTU",
    nam_sinh: "21/12/2003",
    dan_toc_ton_giao: "Kinh/ Không",
    que_quan: "Thanh Trì, Hà Nội",
    trinh_do_hoc_van: "Đại học",
    trinh_do_ly_luan: "Sơ cấp",
    chuc_vu: "quần chúng ưu tú",
    ngay_vao_dang: "15/09/2021",
    ngay_chinh_thuc: "15/09/2022",
    email: "hoangvahe172856@fpt.edu.vn",
  },
];

export interface TestUser {
  id: string;
  username: string;
  email: string;
  role:
    | "PARTY_MEMBER"
    | "OUTSTANDING_INDIVIDUAL"
    | "COMMITTEE"
    | "DEPUTY_SECRETARY"
    | "SECRETARY";
}

const detectRole = (user: RawPartyUser): TestUser["role"] => {
  const name = user.ho_ten.toLowerCase();
  if (name.includes("(phó bí thư)") || name.includes("phó bí thư")) {
    return "DEPUTY_SECRETARY";
  }
  if (name.includes("(bí thư)") || name.includes("bí thư")) {
    return "SECRETARY";
  }
  if (name.includes("(chi ủy viên)") || name.includes("chi ủy viên")) {
    return "COMMITTEE";
  }
  if (user.chuc_vu.toLowerCase().includes("quần chúng ưu tú")) {
    return "OUTSTANDING_INDIVIDUAL";
  }
  return "PARTY_MEMBER";
};

export const testUsers: TestUser[] = rawUsers.map((user) => ({
  id: user.ma_so_nhan_vien,
  username: user.ma_so_nhan_vien,
  email: user.email,
  role: detectRole(user),
}));